### ISSUE TITLE
Swift 5 complains about deallocate

### ISSUE THREAD

**Issue by AccuPhoenix01** [radianttap/JSONWebToken.swift#3]
in `HMACCCommonCrypto.swift` on line 32, compiler complains:

` defer { context.deallocate(capacity: 1) }`
'deallocate(capacity:)' is unavailable: Swift currently only supports freeing entire heap blocks, use deallocate() instead

changing it to `defer { context.deallocate() }` makes compiler happy.

**Comment by radianttap** [comment]
Not sure which branch are you using. This is fixed in `master` and in `podspec` branches. All the others are PR branches for the upstream repo.
